///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String appLoading = 'assets/animations/app_loading.json';
  static const String appLogo = 'assets/images/app_logo_2.png';
  static const String appLogo2 = 'assets/images/app_logo_2.png';

}
